on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        message: [foo, bar, baz]
    steps:
      - name: Print env
        env:
          CORRELATOR: ${{ join([env.GITHUB_JOB, matrix.message], '_') }}
        run: env
