on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        message: [foo, bar, baz]
    steps:
      - name: Print env
        env:
          CORRELATOR: ${{ format('{0}_{1}', env.GITHUB_JOB, matrix.message) }}
        run: env
